dataset_name: water
num_train: 500
num_valid: 500

density_loss: 0.01
max_radius: 15.0

batch_size: 10
train_batch_size: ${dataset.batch_size}
valid_batch_size: 100
test_batch_size: 250

learning_rate: 1e-5
weight_decay: 0.0
num_epochs: 100000
validation_interval: 100
use_gradient_clipping: true
clip_norm: 1.0
pin_memory: True
num_workers: 8
step_size: 10

num_bathes: 1000000
train_batch_interval: 100
validation_batch_interval: 1000
