dataset_full_name: ${dataset.dataset_name}-${dataset.split}
dataset_name: QH9Stable
version: ''
split: random  #[random, size_ood]

# batch_size: 32
batch_size: 32
train_batch_size: ${dataset.batch_size}
valid_batch_size: ${dataset.batch_size}
test_batch_size: 1

# learning_rate: 5e-4
learning_rate: 1e-3
validation_interval: 1
use_gradient_clipping: true
clip_norm: 5.0
pin_memory: False
num_workers: 8

warmup_steps: 1000
total_steps: 260000
lr_end: 1e-7

train_batch_interval: 100
validation_batch_interval: 1000
